package it.orbyta.backend_test_cert.exceptions;

public class PassaggioForRicettaAlreadyExistsException extends Throwable {
    public PassaggioForRicettaAlreadyExistsException(String msg) {
        super(msg);
    }
}
